# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: GitHub Script
        uses: actions/github-script@v3
        with:
          script: |
            console.log("${{ github.event.inputs.environment }}");
            if (!["snd","prd","dev","stg"].includes("${{ github.event.inputs.environment }}")) {
              core.setFailed("${{ github.event.inputs.environment }} is not in snd, prd, dev, stg.");
            }
          debug: true
